export default interface Bet {
   active?: boolean,
   last?: boolean,
   leader?: boolean,
   angel?: boolean,
   bigPhone?: boolean,
   bigPhoneText?: string,
   backForth?: boolean,
   angelImmunized?: boolean,
   firstIndicated?: boolean,
   firstIndicatedText?: string,
   secondIndicated?: boolean,
   secondPlacePercentage?: any,
   secondIndicatedText?: string,
   thirdPlacePercentage?: any,
   thirdIndicated?: boolean,
   thirdIndicatedText?: string,
   fourthIndicated?: boolean,
   fourthIndicatedText?: string,
   fifthIndicated?: boolean,
   fifthIndicatedText?: string,
   eliminatedParticipant?: boolean,
   eliminationPercentage?: any
}