export const customTheme = {
    body: { fontFamily: '"Roboto","Helvetica","Arial",sans-serif'},
  container: { paddingTop: "100px",
    position: "absolute",
    left: "0%",
    right: "0%",
    top: "0%",
    bottom: "0%",
    background: "rgba(27, 130, 252, 0.05)",
    borderRadius: "4px 4px 0px 0px" },
  form: { border: "3px solid #f1f1f1" },
  header: {backgroundColor: "#000",},
  input: {
    width: "100%",
    padding: "12px 20px",
    margin: "8px 0",
    display: "inline-block",
    border: "1px solid #ccc",
    boxSizing: "border-box",
    background: "rgba(27, 130, 252, 0.05)",
    borderRadius: "4px 4px 0px 0px"
  },
  button: {
    position: "static",
    width: "37px",
    height: "44px",
    left: "0px",
    top: "204px",
    background: "#1B82FC",
    boxShadow: "0px 4px 8px rgba(0, 0, 0, 0.15), 0px 2px 10px rgba(0, 0, 0, 0.1)",
    borderRadius: "4px",
    color: "#FFF",
    flex: "none",
    order: 2,
    border: "none",
    alignSelf: "stretch",
    flexGrow: 0,
    margin: "16px 0px"
  },
  label: {
    position: "absolute",
    width: "45px",
    height: "16px",
    left: "0px",
    bottom: "54px",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0.4px",
  },
  inputLabel: {
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0.4px",
  },
  "button:hover": { opacity: 0.8 },
  toast: {
    maxWidth: "60%",
    height: "40px",
    margin: "auto",
    backgroundColor: "#c33",
    color: "#fff",
    textAlign: "center",
    borderRadius: "4px",
    position: "fixed",
    zIndex: 1,
    left: "0",
    right: "0",
    bottom: "30px",
    fontSize: "17px",
    whiteSpace: "nowrap"
  },
}